config/routes.rb
Rails.application.routes.draw do

  resources :flags, only: [:index, :show, :create]
  resources :transcript_speaker_edits, only: [:create]
  resources :transcript_edits, only: [:index, :show, :create]
  resources :transcript_files, only: [:index, :show]
  resources :transcripts, only: [:index, :show]
  resources :collections, only: [:index, :show]

  mount_devise_token_auth_for 'User', at: 'auth', controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  match 'page/:id' => 'default#index', :via => [:get]
  match 'dashboard' => 'default#index', :via => [:get]
  match 'transcript_lines/:id/resolve' => 'transcript_lines#resolve', :via => [:post]
  match 'search' => 'transcripts#search', :via => [:get]

  # admin
  namespace :admin do
    resources :users, only: [:index, :update]
    resources :transcripts, only: [:index]
    resources :flags, only: [:index]
  end
  match 'admin' => 'admin/stats#index', :via => [:get], :as => :admin

  # moderator
  namespace :moderator do
    resources :flags, only: [:index]
  end
  match 'moderator' => 'admin/flags#index', :via => [:get], :as => :moderator

  root :to => 'default#index'
end

app/controllers/transcript_files_controller.rb
class TranscriptFilesController < ApplicationController
  include ActionController::MimeResponds

  before_action :set_transcript, only: [:show, :update, :destroy]
  before_action :set_updated_after, only: [:index]

  # GET /transcripts.json?updated_after=yyyy-mm-dd&page=1
  def index
    @transcripts = Transcript.getUpdatedAfter(@updated_after)
    @opt = transcript_file_params
  end

  # GET /transcript_files/the-uid.json?edits=1
  # GET /transcript_files/the-uid.text?timestamps=1&speakers=1
  # GET /transcript_files/the-uid.vtt?speakers=1
  def show
    @project = Project.getActive
    @transcript_lines = []
    @transcript_line_statuses = []
    @transcript_speakers = []
    @transcript_edits = []
    @opt = transcript_file_params

    if params[:format] == "json"
      @transcript_line_statuses = TranscriptLineStatus.allCached
      @transcript_speakers = TranscriptSpeaker.getByTranscriptId(@transcript.id)
      @transcript_edits = TranscriptEdit.getByTranscript(@transcript.id) if @opt[:edits]

    elsif @opt[:speakers]
      @transcript_lines = TranscriptLine.getByTranscriptWithSpeakers(@transcript.id)

    else
      @transcript_lines = @transcript.transcript_lines
    end
  end

  private

    def set_updated_after
      # default to all time
      @updated_after = 10.years.ago

      # look for parameters
      @updated_after = params[:updated_after].to_datetime unless params[:updated_after].blank?
    end

    def set_transcript
      @transcript = Transcript.find_by(uid: params[:id])
    end

    def transcript_file_params
      params.permit(:original_text, :edits, :timestamps, :speakers)
    end
end

app/views/transcript_files/show.text.erb
Title: <%= @transcript.title %>
Last Updated: <%= @transcript.updated_at.strftime("%Y-%m-%d %l:%M%p") %>
Origin: <%= transcript_url(@transcript) %>
This transcript was generated by <%= @project[:data]["name"] %> and may contain errors.
Read more about how this transcript was created at <%= root_url %>

<% @transcript_lines.each do |line| %>
<%= "#{line.start_time_string} " if @opt[:timestamps] %><%= "<#{line.speaker_name}> " if @opt[:speakers] && !line.speaker_name.blank? %><%= "<Multiple Speakers> " if @opt[:speakers] && line.speaker_id < 0 %><%= line.best_text %>
<% end %>

app/views/transcript_files/show.vtt.erb
WEBVTT

NOTE
Title: <%= @transcript.title %>
Last Updated: <%= @transcript.updated_at.strftime("%Y-%m-%d %l:%M%p") %>
Origin: <%= transcript_url(@transcript) %>
This transcript was generated by <%= @project[:data]["name"] %> and may contain errors.
Read more about how this transcript was created at <%= root_url %>

<% @transcript_lines.each do |line| %>
<%= line.start_time_string %> --> <%= line.end_time_string %>
<%= raw "<v #{line.speaker_name}> " if @opt[:speakers] && !line.speaker_name.blank? %><%= raw "<v Multiple Speakers> " if @opt[:speakers] && line.speaker_id < 0 %><%= raw line.best_text %>

<% end %>